// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase configuration
  // You can get these values from Firebase Console > Project Settings

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHKxeXKXKAaRWBD6vISwMLcDri2W4AGuU',
    appId: '1:824941697504:android:f0c13e2cc637efe966f385',
    messagingSenderId: '824941697504',
    projectId: 'streamline-1998b',
    storageBucket: 'streamline-1998b.firebasestorage.app',
  );

  // Or run: flutterfire configure

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUEHbP3DsNNxjV817z2vsVhsBDl-N5YKQ',
    appId: '1:824941697504:ios:6892bb64b56cf00766f385',
    messagingSenderId: '824941697504',
    projectId: 'streamline-1998b',
    storageBucket: 'streamline-1998b.firebasestorage.app',
    iosBundleId: 'com.example.streamline',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbe3gLrDyvQ8NDKXIleOgf2Mtcvj7I_b0',
    appId: '1:824941697504:web:fbb77163738904b766f385',
    messagingSenderId: '824941697504',
    projectId: 'streamline-1998b',
    authDomain: 'streamline-1998b.firebaseapp.com',
    storageBucket: 'streamline-1998b.firebasestorage.app',
    measurementId: 'G-8SZH4D8DFH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUEHbP3DsNNxjV817z2vsVhsBDl-N5YKQ',
    appId: '1:824941697504:ios:6892bb64b56cf00766f385',
    messagingSenderId: '824941697504',
    projectId: 'streamline-1998b',
    storageBucket: 'streamline-1998b.firebasestorage.app',
    iosBundleId: 'com.example.streamline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbe3gLrDyvQ8NDKXIleOgf2Mtcvj7I_b0',
    appId: '1:824941697504:web:3296b8940fb7c34966f385',
    messagingSenderId: '824941697504',
    projectId: 'streamline-1998b',
    authDomain: 'streamline-1998b.firebaseapp.com',
    storageBucket: 'streamline-1998b.firebasestorage.app',
    measurementId: 'G-WSQGZ1ZDHK',
  );

}